In [1]:
##Import libraries
import pandas as pd

In [3]:
##Load the file
df = pd.read_excel(r"C:\Users\user\Desktop\Internship\SkillCraft Tecnology\Global Superstore.xlsx")

In [4]:
df.head()

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-01,CA-2011-130813,...,19,Consumer,2011-01-05,Second Class,4.37,California,Paper,2011,North America,1
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-01,CA-2011-148614,...,19,Consumer,2011-01-07,Standard Class,0.94,California,Paper,2011,North America,1
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-01-01,CA-2011-118962,...,21,Consumer,2011-01-07,Standard Class,1.81,California,Paper,2011,North America,1
3,Office Supplies,Los Angeles,United States,,Chad Sievert,0.0,US,1,2011-01-01,CA-2011-118962,...,111,Consumer,2011-01-07,Standard Class,4.59,California,Paper,2011,North America,1
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-01-01,CA-2011-146969,...,6,Consumer,2011-01-07,Standard Class,1.32,California,Paper,2011,North America,1

In [5]:
##Check the number of rows and columns
df.shape

(51290, 27)

In [6]:
##View all column names
df.columns

Index(['Category', 'City', 'Country', 'Customer ID', 'Customer Name',
       'Discount', 'Market', 'ji_lu-shu', 'Order Date', 'Order ID',
       'Order Priority', 'Product ID', 'Product Name', 'Profit', 'Quantity',
       'Region', 'Row ID', 'Sales', 'Segment', 'Ship Date', 'Ship Mode',
       'Shipping Cost', 'State', 'Sub-Category', 'Year', 'Market2', 'weeknum'],
      dtype='object')

In [7]:
##Check the first few records
df.head()

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-01,CA-2011-130813,...,19,Consumer,2011-01-05,Second Class,4.37,California,Paper,2011,North America,1
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-01,CA-2011-148614,...,19,Consumer,2011-01-07,Standard Class,0.94,California,Paper,2011,North America,1
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-01-01,CA-2011-118962,...,21,Consumer,2011-01-07,Standard Class,1.81,California,Paper,2011,North America,1
3,Office Supplies,Los Angeles,United States,,Chad Sievert,0.0,US,1,2011-01-01,CA-2011-118962,...,111,Consumer,2011-01-07,Standard Class,4.59,California,Paper,2011,North America,1
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-01-01,CA-2011-146969,...,6,Consumer,2011-01-07,Standard Class,1.32,California,Paper,2011,North America,1

In [8]:
##Check the last few records
df.tail()

,Category,City,Country,Customer ID,Customer Name,Discount,Market,ji_lu-shu,Order Date,Order ID,...,Sales,Segment,Ship Date,Ship Mode,Shipping Cost,State,Sub-Category,Year,Market2,weeknum
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-31,CA-2014-109701,...,69,Corporate,2015-01-01,Same Day,5.15,California,Binders,2014,North America,53
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.2,US,1,2014-12-31,CA-2014-109701,...,9,Corporate,2015-01-01,Same Day,0.44,California,Binders,2014,North America,53
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.2,US,1,2014-12-31,CA-2014-106964,...,12,Home Office,2015-01-02,First Class,0.31,California,Binders,2014,North America,53
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.2,US,1,2014-12-31,CA-2014-145219,...,90,Home Office,2015-01-02,First Class,15.95,California,Binders,2014,North America,53
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.2,US,1,2014-12-31,CA-2014-121398,...,154,Corporate,2015-01-06,Standard Class,9.59,California,Binders,2014,North America,53

In [9]:
##Check data types
df.dtypes

Category                  object
City                      object
Country                   object
Customer ID               object
Customer Name             object
Discount                 float64
Market                    object
ji_lu-shu                  int64
Order Date        datetime64[ns]
Order ID                  object
Order Priority            object
Product ID                object
Product Name              object
Profit                   float64
Quantity                   int64
Region                    object
Row ID                     int64
Sales                      int64
Segment                   object
Ship Date         datetime64[ns]
Ship Mode                 object
Shipping Cost            float64
State                     object
Sub-Category              object
Year                       int64
Market2                   object
weeknum                    int64
dtype: object

In [10]:
##Check missing values
df.isnull().sum()

Category          0
City              0
Country           0
Customer ID       0
Customer Name     0
Discount          0
Market            0
ji_lu-shu         0
Order Date        0
Order ID          0
Order Priority    0
Product ID        0
Product Name      0
Profit            0
Quantity          0
Region            0
Row ID            0
Sales             0
Segment           0
Ship Date         0
Ship Mode         0
Shipping Cost     0
State             0
Sub-Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [12]:
##Check duplicate rows
df.duplicated().sum()

np.int64(0)

In [13]:
##Remove duplicate rows
df = df.drop_duplicates()

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
##Check unique values in important columns
df['Category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [16]:
df['Region'].unique()

array(['West', 'East', 'South', 'Central', 'Africa', 'Central Asia',
       'North Asia', 'Caribbean', 'North', 'EMEA', 'Oceania',
       'Southeast Asia', 'Canada'], dtype=object)

In [17]:
df['Segment'].unique()

array(['Consumer', 'Home Office', 'Corporate'], dtype=object)

In [18]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Same Day', 'First Class'],
      dtype=object)

In [19]:
df['Order Priority'].unique()

array(['High', 'Medium', 'Critical', 'Low'], dtype=object)

In [20]:
df.nunique()

Category              3
City               3636
Country             147
Customer ID        4874
Customer Name       795
Discount             27
Market                7
ji_lu-shu             1
Order Date         1461
Order ID          25035
Order Priority        4
Product ID        10292
Product Name       3788
Profit            24575
Quantity             14
Region               13
Row ID            51290
Sales              2246
Segment               3
Ship Date          1452
Ship Mode             4
Shipping Cost     16877
State              1094
Sub-Category         17
Year                  4
Market2               6
weeknum              53
dtype: int64

In [21]:
##Check for invalid values
df.describe()

,Discount,ji_lu-shu,Order Date,Profit,Quantity,Row ID,Sales,Ship Date,Shipping Cost,Year,weeknum
count,51290.000000,51290.0,51290,51290.000000,51290.000000,51290.00000,51290.000000,51290,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,2013-04-11 09:13:39.107038720,28.610982,3.476545,25645.50000,246.498440,2013-04-16 03:12:47.728601856,26.375818,2012.777208,26.958725
min,0.000000,1.0,2011-01-01 00:00:00,-6599.978000,1.000000,1.00000,0.000000,2011-01-02 00:00:00,0.002000,2011.000000,1.000000
25%,0.000000,1.0,2012-05-07 00:00:00,0.000000,2.000000,12823.25000,31.000000,2012-05-13 00:00:00,2.610000,2012.000000,14.000000
50%,0.000000,1.0,2013-05-31 00:00:00,9.240000,3.000000,25645.50000,85.000000,2013-06-06 00:00:00,7.790000,2013.000000,27.000000
75%,0.200000,1.0,2014-04-09 00:00:00,36.810000,5.000000,38467.75000,251.000000,2014-04-15 00:00:00,24.450000,2014.000000,40.000000
max,0.850000,1.0,2014-12-31 00:00:00,8399.976000,14.000000,51290.00000,22638.000000,2015-01-06 00:00:00,933.570000,2014.000000,53.000000
std,0.212280,0.0,NaN,174.340972,2.278766,14806.29199,487.567175,NaN,57.296810,1.098931,15.066490

In [22]:
df['Sales'].describe()

count    51290.000000
mean       246.498440
std        487.567175
min          0.000000
25%         31.000000
50%         85.000000
75%        251.000000
max      22638.000000
Name: Sales, dtype: float64

In [23]:
df['Sales'].describe()

count    51290.000000
mean       246.498440
std        487.567175
min          0.000000
25%         31.000000
50%         85.000000
75%        251.000000
max      22638.000000
Name: Sales, dtype: float64

In [24]:
##Convert Order Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [25]:
df['Order Date'].head()

0   2011-01-01
1   2011-01-01
2   2011-01-01
3   2011-01-01
4   2011-01-01
Name: Order Date, dtype: datetime64[ns]

In [26]:
##Check the Year column
df['Year'].dtype

dtype('int64')

In [27]:
df['Year'].unique()

array([2011, 2012, 2013, 2014])

In [28]:
##Check numerical columns
numeric_columns = [
    'Discount',
    'Profit',
    'Quantity',
    'Sales',
    'Shipping Cost',
    'Year',
    'weeknum'
]

df[numeric_columns].dtypes

Discount         float64
Profit           float64
Quantity           int64
Sales              int64
Shipping Cost    float64
Year               int64
weeknum            int64
dtype: object

In [29]:
for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [30]:
##Check categorical columns
categorical_columns = [
    'Category',
    'City',
    'Country',
    'Market',
    'Order Priority',
    'Region',
    'Segment',
    'Ship Mode',
    'State',
    'Sub-Category',
    'Market2'
]

for col in categorical_columns:
    df[col] = df[col].astype('category')

In [31]:
df[categorical_columns].dtypes

Category          category
City              category
Country           category
Market            category
Order Priority    category
Region            category
Segment           category
Ship Mode         category
State             category
Sub-Category      category
Market2           category
dtype: object

In [32]:
##Check the cleaned dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  category
 1   City            51290 non-null  category
 2   Country         51290 non-null  category
 3   Customer ID     51290 non-null  object
 4   Customer Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  category
 7   ji_lu-shu       51290 non-null  int64
 8   Order Date      51290 non-null  datetime64[ns]
 9   Order ID        51290 non-null  object
 10  Order Priority  51290 non-null  category
 11  Product ID      51290 non-null  object
 12  Product Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  category
 16  Row ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  category
 19  Ship Date       51290 non-null  datetime64[ns]
 20  Ship Mode       51290 non-null  category
 21  Shipping Cost   51290 non-null  float64
 22  State           51290 non-null  category
 23  Sub-Category    51290 non-null  category
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  category
 26  weeknum         51290 non-null  int64
dtypes: category(11), datetime64[ns](2), float64(3), int64(6), object(5)
memory usage: 7.1+ MB

In [33]:
##Final missing-value check
df.isnull().sum()

Category          0
City              0
Country           0
Customer ID       0
Customer Name     0
Discount          0
Market            0
ji_lu-shu         0
Order Date        0
Order ID          0
Order Priority    0
Product ID        0
Product Name      0
Profit            0
Quantity          0
Region            0
Row ID            0
Sales             0
Segment           0
Ship Date         0
Ship Mode         0
Shipping Cost     0
State             0
Sub-Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [34]:
df.isnull().sum().sum()

np.int64(0)

In [35]:
df.duplicated().sum()

np.int64(0)

In [37]:
##Export the cleaned dataset
df.to_excel("Global_Superstore_Cleaned.xlsx", index=False)